name: GitHub Context

on:
 workflow_dispatch:

jobs:
 echo-github-context:
  runs-on: ubuntu-latest
  steps:
    - name: "Display Info"
      run: |
       echo 'Event name ${{github.event_name}}'
       echo 'Reference details ${{github.ref}}'
       echo 'ref name ${{github.ref_name}}'
       echo 'Commit SHA ${{github.sha}}'
       echo 'Run Id ${{github.run_id}}'
       echo 'Run number ${{github.run_number}}'
       
