name: Matrix

on:
 workflow_dispatch

jobs:
 matrix-echo:
  runs-on: ${{matrix.os}}
  strategy:
   matrix:
    os: 
     - ubuntu-latest
     - windows-latest
    node-version: [v22, v21]
  steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
         node-version: ${{matrix.node-version}}
      - name: Perform test
        run: echo 'Display ${{matrix.os}} and ${{matrix.node-version}}'
